/*
 * generated by Xtext 2.29.0
 */
package snn.apds.dsl.prototypes


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PrototypeStandaloneSetup extends PrototypeStandaloneSetupGenerated {

	def static void doSetup() {
		new PrototypeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
