/*
 * generated by Xtext 2.29.0
 */
package snn.apds.dsl.subjects


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SubjectStandaloneSetup extends SubjectStandaloneSetupGenerated {

	def static void doSetup() {
		new SubjectStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
