/*
 * generated by Xtext 2.29.0
 */
package snn.apds.dsl.subjects


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SubjectRuntimeModule extends AbstractSubjectRuntimeModule {
}
